server:
  port: 8082
  servlet:
    context-path: /api

spring:
  application:
    name: pacientes-service
  
  datasource:
    url: jdbc:postgresql://localhost:5432/pacientes_db
    username: ${DB_USERNAME:postgres}
    password: ${DB_PASSWORD:password}
    driver-class-name: org.postgresql.Driver
  
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
  
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8080/api/auth
  
  cache:
    type: simple
  
  mail:
    host: ${MAIL_HOST:smtp.gmail.com}
    port: ${MAIL_PORT:587}
    username: ${MAIL_USERNAME:}
    password: ${MAIL_PASSWORD:}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics
  endpoint:
    health:
      show-details: when-authorized

logging:
  level:
    com.gestioneps.pacientes: DEBUG
    org.springframework.security: DEBUG
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} - %msg%n"
    file: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"

# Configuración específica para historias clínicas
historias-clinicas:
  storage:
    path: ${HC_STORAGE_PATH:./storage/historias-clinicas}
  documents:
    max-size: ${HC_MAX_SIZE:10MB}
    allowed-types: pdf,doc,docx,jpg,jpeg,png
  backup:
    enabled: ${HC_BACKUP_ENABLED:true}
    schedule: "0 0 2 * * ?"
