server:
  port: 8081

spring:
  application:
    name: gateway
  cloud:
    gateway:
      globalcors:
        cors-configurations:
          '[/**]':
            allowedOriginPatterns:
              - "*"
            allowedMethods:
              - "GET"
              - "POST"
              - "PUT"
              - "DELETE"
              - "OPTIONS"
              - "PATCH"
              - "HEAD"
            allowedHeaders:
              - "*"
            exposedHeaders:
              - "Authorization"
              - "Content-Type"
              - "Content-Disposition"
              - "X-Requested-With"
            allowCredentials: true
            maxAge: 3600
      routes:
        # Rutas específicas primero (orden importa)
        - id: auth_route
          uri: http://localhost:8080
          predicates:
            - Path=/api/auth/**
          filters:
            - StripPrefix=0
        - id: users_route
          uri: http://localhost:8080
          predicates:
            - Path=/api/users/**
          filters:
            - StripPrefix=0
        - id: pacientes_route
          uri: http://localhost:8082
          predicates:
            - Path=/api/pacientes/**
          filters:
            - StripPrefix=0
        - id: historias_route
          uri: http://localhost:8082
          predicates:
            - Path=/api/historias-clinicas/**
          filters:
            - StripPrefix=0
        - id: consultas_route
          uri: http://localhost:8082
          predicates:
            - Path=/api/consultas/**
          filters:
            - StripPrefix=0
        - id: documentos_route
          uri: http://localhost:8082
          predicates:
            - Path=/api/documentos/**
          filters:
            - StripPrefix=0
        - id: citas_route
          uri: http://localhost:8082
          predicates:
            - Path=/api/citas/**
          filters:
            - StripPrefix=0
        - id: codigos_cups_route
          uri: http://localhost:8082
          predicates:
            - Path=/api/codigos-cups/**
          filters:
            - StripPrefix=0
        - id: empleados_route
          uri: http://localhost:8084
          predicates:
            - Path=/api/empleados/**
          filters:
            - StripPrefix=0
        - id: nomina_route
          uri: http://localhost:8084
          predicates:
            - Path=/api/nomina/**
          filters:
            - StripPrefix=0
      default-filters:
        - StripPrefix=0
        - AddRequestHeader=X-Forwarded-For, #{request.remoteAddress}
  # Redis configuration for blacklist - commented out
  # data:
  #   redis:
  #     host: redis
  #     port: 6379


management:
  endpoints:
    web:
      exposure:
        include: health,info
  health:
    redis:
      enabled: false

logging:
  level:
    root: INFO
  '[com.gateway]': DEBUG