server:
  port: 8081

spring:
  application:
    name: gateway
  cloud:
    gateway:
      routes:
        # Rutas específicas primero (orden importa)
        - id: auth_route
          uri: http://localhost:8080
          predicates:
            - Path=/api/auth/**
          filters:
            - StripPrefix=0
        - id: pacientes_route
          uri: lb://PACIENTES-SERVICE
          predicates:
            - Path=/api/pacientes/**
          filters:
            - StripPrefix=0
      default-filters:
        - StripPrefix=0
        - AddRequestHeader=X-Forwarded-For, #{request.remoteAddress}
  # Redis configuration for blacklist
  data:
    redis:
      host: localhost
      port: 6379

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

management:
  endpoints:
    web:
      exposure:
        include: health,info

logging:
  level:
    root: INFO
  '[com.gateway]': DEBUG